version: 2.1

orbs:
  k8s: circleci/kubernetes@1.3.1
  gh: circleci/github-cli@2.3.0
  golang: circleci/go@1.7.2
  retry: kimh/run-with-retry@1.0.0

executors:
  machine-medium:
    machine:
      image: ubuntu-2204:2023.04.2
      docker_layer_caching: true
    working_directory: ~/repo
    resource_class: medium
  machine-large:
    machine:
      image: ubuntu-2204:2023.04.2
      docker_layer_caching: true
    working_directory: ~/repo
    resource_class: large

filter-for-tags: &filter-for-tags
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

commands:
  docker_login:
    steps:
      - run:
          # https://circleci.com/docs/building-docker-images/#run-docker-commands-using-the-machine-executor
          name: Docker Auth
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
  install_software:
    steps:
      - k8s/install
      - golang/install:
          cache: true
          version: 1.21.5
      - run:
          name: Install Kind
          command: |
            if [ ! -f ~/bin/kind ]; then
              curl -L https://github.com/kubernetes-sigs/kind/releases/download/v0.20.0/kind-linux-amd64 -o ~/bin/kind
              chmod +x ~/bin/kind
            fi
      - run:
          name: Install Helm
          command: |
            curl -L https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz -o helm.tar.gz
            tar -xvf helm.tar.gz
            mv linux-amd64/helm ~/bin/helm
            chmod +x ~/bin/helm
            rm -rf linux-amd64/
            rm helm.tar.gz
      - run:
          name: Install yq
          command: |
            curl -L https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -o yq
            mv yq ~/bin/yq
            chmod +x ~/bin/yq
      - run:
          name: Install Flux
          command: |
            curl -L https://github.com/fluxcd/flux2/releases/download/v0.41.2/flux_0.41.2_linux_amd64.tar.gz -o flux.tar.gz
            tar -xvf flux.tar.gz
            mv flux ~/bin/flux
            chmod +x ~/bin/flux
            rm flux.tar.gz
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: |
            go mod download
  setup_git:
    steps:
      - add_ssh_keys:
          # Add github deploy key
          # https://circleci.com/docs/github-integration#create-a-github-deploy-key
          fingerprints:
            - "5e:1e:ea:52:8b:1b:ad:a2:66:1a:40:98:a3:f5:96:f5"
      - run:
          # see https://circleci.com/docs/github-integration#establish-the-authenticity-of-an-ssh-host
          name: setup git
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com > ~/.ssh/known_hosts

            git config --global user.name "syntassodev"
            git config --global user.email "kratix@syntasso.io"

jobs:
  clone-helm-charts:
    executor: machine-medium
    steps:
      - run:
          name: Clone helm charts
          command: |
            git clone --depth 1 git@github.com:syntasso/helm-charts.git ~/repo/charts
      - persist_to_workspace:
          root: .
          paths:
            - charts/

  clone-kratix:
    executor: machine-medium
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  govulncheck:
    executor: machine-medium
    steps:
      - install_software
      - run:
          name: install govulncheck
          command: |
            set -o pipefail
            go install golang.org/x/vuln/cmd/govulncheck@latest
      - run:
          name: run check
          command: govulncheck ./...

  unit-tests:
    executor: machine-medium
    steps:
      - install_software
      - run:
          name: Run tests
          command: |
            make test
            make -C work-creator test

  system-tests-git:
    executor: machine-large
    steps:
      - install_software
      - run:
          name: System tests
          command: |
            SYSTEM_TEST_STORE_TYPE=git DOCKER_BUILDKIT=1 ACK_GINKGO_RC=true make system-test

  system-tests-bucket:
    executor: machine-large
    steps:
      - install_software
      - run:
          name: System tests
          command: |
            SYSTEM_TEST_STORE_TYPE=bucket DOCKER_BUILDKIT=1 ACK_GINKGO_RC=true make system-test

  e2e-demo-test-helm-git:
    executor: machine-large
    steps:
      - install_software
      - run:
          name: Create Destinations and helm install
          command: |
            make distribution
            export DOCKER_BUILDKIT=1

            # setup platform and install GitStateStore
            kind create cluster --image kindest/node:v1.27.3 --name platform --config hack/platform/kind-platform-config.yaml
            make install-cert-manager
            make build-and-load-kratix
            make build-and-load-worker-creator
            helm install kratix charts/kratix/ -f hack/platform/helm-values-gitea.yaml
            kubectl --context kind-platform apply --filename "hack/platform/gitea-install.yaml"
            kubectl --context kind-platform wait --for=condition=Ready --timeout=300s -n gitea pod -l app.kubernetes.io/instance=gitea

            # setup worker cluster and register as destination
            kind create cluster --image kindest/node:v1.27.3 --name worker --config hack/destination/kind-worker-config.yaml
            helm install kratix-destination charts/kratix-destination/ -f hack/destination/helm-values-gitea.yaml
            kubectl --context kind-worker wait --for=condition=Ready --timeout=300s -n default kustomization kratix-workload-resources
      - run:
          name: Verify Jenkins
          command: |
            ./scripts/install-jenkins.sh

  e2e-demo-test-helm-bucket:
    executor: machine-large
    steps:
      - install_software
      - run:
          name: Create Destinations and helm install
          command: |
            make distribution
            export DOCKER_BUILDKIT=1

            # setup platform and install BucketStateStore
            kind create cluster --image kindest/node:v1.27.3 --name platform --config hack/platform/kind-platform-config.yaml
            make install-cert-manager
            make build-and-load-kratix
            make build-and-load-worker-creator
            helm install kratix charts/kratix/ -f hack/platform/helm-values-minio.yaml
            kubectl --context kind-platform apply --filename "hack/platform/minio-install.yaml"
            kubectl --context kind-platform wait --for=condition=Ready --timeout=300s -n kratix-platform-system pod -l run=minio

            # setup worker cluster and register as destination
            kind create cluster --image kindest/node:v1.27.3 --name worker --config hack/destination/kind-worker-config.yaml
            helm install kratix-destination charts/kratix-destination/ -f hack/destination/helm-values-minio.yaml
            kubectl --context kind-platform apply --filename config/samples/platform_v1alpha1_worker.yaml
            kubectl --context kind-worker wait --for=condition=Ready --timeout=300s -n kratix-worker-config kustomization kratix-workload-resources
      - run:
          name: Verify Jenkins
          command: |
            ./scripts/install-jenkins.sh

  git-merge:
    executor: machine-large
    steps:
      - install_software
      - setup_git
      - run:
          name: Merge dev to main
          command: |
            ./scripts/merge-dev.sh
      - persist_to_workspace:
          root: .
          paths:
            - .

  generate-demo-image-list:
    executor: machine-large
    steps:
      - attach_workspace:
          at: .
      - install_software
      - run:
          name: Generate demo image list
          command: |
            cd ./demo/
            ./scripts/generate-demo-image-list.sh
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-and-push-images:
    docker:
      - image: cimg/base:current
    resource_class: large
    parameters:
      image:
        type: string
    environment:
      VERSION: << pipeline.git.tag >>
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 20.10.23
          docker_layer_caching: true
      - docker_login
      - run:
          name: Build and push images
          command: |
            ./scripts/build-images << parameters.image >>

  git-push-to-dev:
    executor: machine-large
    steps:
      - attach_workspace:
          at: .
      - setup_git
      - run:
          name: Push dev
          command: |
            git add -f demo/
            # below command exits 0 when nothing is added
            git diff --cached --quiet && exit 0 || true
            git commit -m"update demo image list"
            git push origin dev

  git-push:
    executor: machine-large
    steps:
      - attach_workspace:
          at: .
      - setup_git
      - run:
          name: Push main
          command: |
            git add -f config/
            git add -f demo/demo-image-list
            git add -f distribution/kratix.yaml
            git add -f distribution/single-cluster/
            git add -f charts/kratix/crds/platform_kratix_io_crds.yaml
            git add -f charts/kratix/templates/distribution.yaml
            git commit --amend --no-edit
            git push origin main

  generate-release-distribution:
    executor: machine-large
    environment:
      VERSION: << pipeline.git.tag >>
    steps:
      - attach_workspace:
          at: .
      - install_software
      - run:
          name: Generate new distribution
          command: |
            ./scripts/make-distribution
      - persist_to_workspace:
          root: .
          paths:
            - .

  tag-new-version:
    executor: machine-large
    steps:
      - attach_workspace:
          at: .
      - setup_git
      - run:
          name: bump minor version and push tag
          command: |
            latest_tag=$(git describe --tags --abbrev=0)
            minor=$(echo "${latest_tag}" | cut -d '.' -f 2)
            new_tag="v0.$(($minor+1)).0"

            git tag -a $new_tag -m"${new_tag}"
            git push origin $new_tag

  gh-release:
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - attach_workspace:
          at: .
      - gh/setup
      - run:
          name: Release
          command: |
            gh config set prompt disabled
            gh release create <<pipeline.git.tag>> --title <<pipeline.git.tag>> ./distribution/**/*.yaml ./distribution/*.yaml

workflows:
  run-ci:
    jobs:
      - clone-kratix
      - clone-helm-charts
      - unit-tests:
          requires: [clone-kratix, clone-helm-charts]
      - system-tests-git:
          requires: [clone-kratix, clone-helm-charts]
      - system-tests-bucket:
          requires: [clone-kratix, clone-helm-charts]
      - e2e-demo-test-helm-bucket:
          requires: [clone-kratix, clone-helm-charts]
      - e2e-demo-test-helm-git:
          requires: [clone-kratix, clone-helm-charts]
      ### ONLY DEV
      - git-merge:
          requires:
            - unit-tests
            - system-tests-git
            - system-tests-bucket
            - e2e-demo-test-helm-git
            - e2e-demo-test-helm-bucket
          filters:
            branches:
              only: dev
      - build-and-push-images:
          requires: [git-merge]
          matrix:
            parameters:
              image: [kratix, work-creator, samples]
      - git-push:
          requires: [build-and-push-images]
      ### END ONLY DEV
      ### ONLY MAIN
      - tag-new-version:
          requires:
            - unit-tests
            - system-tests-git
            - system-tests-bucket
            - e2e-demo-test-helm-git
            - e2e-demo-test-helm-bucket
          filters:
            branches:
              only: main
      ### END ONLY MAIN

  release:
    jobs:
      - clone-kratix:
          <<: *filter-for-tags
      - build-and-push-images:
          <<: *filter-for-tags
          requires: [clone-kratix]
          matrix:
            parameters:
              image: [kratix, work-creator, samples]
      - generate-release-distribution:
          <<: *filter-for-tags
          requires: [clone-kratix]
      - gh-release:
          <<: *filter-for-tags
          requires: [build-and-push-images, generate-release-distribution]

  update-demo:
    triggers:
      - schedule:
          cron: "0 0 * * 1-5"
          filters:
            branches:
              only: [dev]
    jobs:
      - clone-kratix
      - generate-demo-image-list:
          requires: [clone-kratix]
      - git-push-to-dev:
          requires: [generate-demo-image-list]

  security-scan:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: [main]
    jobs:
      - clone-kratix
      - govulncheck:
          requires: [clone-kratix]
